<CamerScreen>
    GridLayout:
        cols: 1
        padding: 10
        spacing: 10
        Camera : 
            id: camera
            resolution: (640,648)
            play: False
            size_hint_y:0.8
        Button:
            id:camera_button
            text: 'Start Camera'
            on_press:root.start() if root.ids.camera.play==False else root.stop()
            size_hint_y:0.1
            background_normal:
            background_down:
        Button:
            text: 'Capture'
            on_press:root.capture()
            size_hint_y:0.1


<ImageScreen>:
    GridLayout:
        padding:10
        spacing:10
        cols:1
        Image:
            id:img
            size_hint_y:0.7
        Button:
            text: 'create shareable link'
            on_press:root.create_link()
        Label:
            id:link
            text:''
    GridLayout:
        cols:2
        size_hint_y:0.1
        Button:
            text:'Copy Link'
            on_press:root.copy_link()
        Button:
            text:'Open_link'
            on_press:root.create_link()

<RootWidget>:
    CameraScreen:
        id:camera_screen
        name:'camera_screen'